import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Link from "next/link";
import { Toaster } from 'sonner'
import { ArrowUpDown, Book, User } from "lucide-react";
import { auth } from "@/auth";
import { cn } from "@/lib/utils";
import { headers } from "next/headers";
import MenuSide from "./_components/MenuSide";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  const headersList = await headers();
  const pathname = headersList.get("x-invoke-path") || "/";
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Toaster />
        <SessionProvider>
          <div className="flex">
            {session?.user && (
              <MenuSide />
            )}
            <div className="flex-1 max-h-dvh overflow-y-auto">{children}</div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
