import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <div className="bg-pink-300 flex">
            <div className="bg-gray-300 h-dvh min-w-[200px]">
              <div>side bar</div>
              <Link href={`/book`}>
                <div>หนังสือ</div>
              </Link>
            </div>
            <div className="flex-1 max-h-dvh overflow-y-auto">{children}</div>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
